import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Clearing database...');
  await prisma.review.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.subscription.deleteMany();
  await prisma.product.deleteMany();
  await prisma.farmer.deleteMany();
  await prisma.user.deleteMany();

  console.log('Seeding users...');
  const adminPassword = bcrypt.hashSync('admin123', 10);
  const customerPassword = bcrypt.hashSync('customer123', 10);

  const admin = await prisma.user.create({
    data: {
      email: 'admin@freshbasket.com',
      password: adminPassword,
      name: 'Admin Manager',
      role: 'ADMIN',
    },
  });

  const customer = await prisma.user.create({
    data: {
      email: 'customer@gmail.com',
      password: customerPassword,
      name: 'John Doe',
      role: 'CUSTOMER',
    },
  });

  console.log('Seeding farmers...');
  const farmerJohn = await prisma.farmer.create({
    data: {
      name: 'Farmer John',
      location: 'Napa Valley, CA',
      story: 'John has been growing organic apples and berries for over three decades using eco-friendly practices.',
      image: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=400&q=80',
      lat: 38.2975,
      lng: -122.2869,
    },
  });

  const farmerMaria = await prisma.farmer.create({
    data: {
      name: 'Farmer Maria',
      location: 'Sunny Glades, FL',
      story: 'Maria specializes in citrus fruits and tropical varieties, utilizing natural rainwater irrigation.',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
      lat: 25.7617,
      lng: -80.1918,
    },
  });

  const farmerKen = await prisma.farmer.create({
    data: {
      name: 'Farmer Ken',
      location: 'Hood River, OR',
      story: 'Ken utilizes high-altitude mountain waters to grow crisp stone fruits and premium grapes.',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      lat: 45.7082,
      lng: -121.5139,
    },
  });

  const farmerRajesh = await prisma.farmer.create({
    data: {
      name: 'Farmer Rajesh',
      location: 'Shimla, Himachal Pradesh, India',
      story: 'Nestled in the foothills of the Himalayas, Rajesh grows premium apples and sweet stone fruits using traditional mountain farming.',
      image: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=400&q=80',
      lat: 31.1048,
      lng: 77.1734,
    },
  });

  const farmerSunita = await prisma.farmer.create({
    data: {
      name: 'Farmer Sunita',
      location: 'Ratnagiri, Maharashtra, India',
      story: 'Sunita manages multi-generational orchards along the Konkan coast, famous for cultivating authentic, sun-ripened Alphonso mangoes.',
      image: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=400&q=80',
      lat: 16.9902,
      lng: 73.3120,
    },
  });

  const farmerDevendra = await prisma.farmer.create({
    data: {
      name: 'Farmer Devendra',
      location: 'Nagpur, Maharashtra, India',
      story: 'Devendra employs micro-irrigation techniques to grow rich, succulent mandarin oranges and citric varieties in Central India.',
      image: 'https://images.unsplash.com/photo-1500937386664-56d159f87b81?auto=format&fit=crop&w=400&q=80',
      lat: 21.1458,
      lng: 79.0882,
    },
  });

  console.log('Seeding products...');
  const products = [
    // --- Original Products ---
    {
      name: 'Organic Honeycrisp Apples',
      description: 'Exceptionally crisp and sweet organic apples freshly picked from Napa Valley orchards.',
      category: 'Stone Fruit',
      price: 4.99,
      stock: 45,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
      calories: 52,
      protein: 0.3,
      carbs: 14,
      vitamins: 'Vitamin C, Potassium, Vitamin K',
      season: 'Autumn',
      isFeatured: true,
      farmerId: farmerJohn.id,
    },
    {
      name: 'Premium Cavendish Bananas',
      description: 'Sweet and perfectly ripe yellow bananas, rich in potassium and energy.',
      category: 'Tropical',
      price: 2.29,
      stock: 80,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      calories: 89,
      protein: 1.1,
      carbs: 23,
      vitamins: 'Vitamin B6, Vitamin C, Potassium',
      season: 'All',
      isFeatured: true,
      farmerId: farmerMaria.id,
    },
    {
      name: 'Valencia Oranges',
      description: 'Juicy and sweet oranges perfect for freshly squeezed morning juice.',
      category: 'Citrus',
      price: 3.49,
      stock: 50,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=600&q=80',
      calories: 47,
      protein: 0.9,
      carbs: 12,
      vitamins: 'Vitamin C, Folate, Thiamin',
      season: 'Winter',
      isFeatured: true,
      farmerId: farmerMaria.id,
    },
    {
      name: 'Alphonso Mangoes',
      description: 'The king of fruits! Incredibly sweet, rich, and aromatic tropical mangoes.',
      category: 'Tropical',
      price: 6.99,
      stock: 15,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
      calories: 60,
      protein: 0.8,
      carbs: 15,
      vitamins: 'Vitamin C, Vitamin A, Vitamin B6',
      season: 'Summer',
      isFeatured: true,
      farmerId: farmerMaria.id,
    },
    {
      name: 'Sweet Ruby Strawberries',
      description: 'Freshly harvested organic strawberries, ruby red and burst with flavor.',
      category: 'Berries',
      price: 5.99,
      stock: 60,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
      calories: 32,
      protein: 0.7,
      carbs: 7.7,
      vitamins: 'Vitamin C, Manganese, Folate',
      season: 'Spring',
      isFeatured: true,
      farmerId: farmerJohn.id,
    },
    {
      name: 'Zesty Kiwi Fruits',
      description: 'Tangy and vitamin-rich green kiwis with a refreshing tropical flavor profile.',
      category: 'Tropical',
      price: 4.49,
      stock: 30,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1585059895524-72359e061381?auto=format&fit=crop&w=600&q=80',
      calories: 61,
      protein: 1.1,
      carbs: 15,
      vitamins: 'Vitamin C, Vitamin K, Vitamin E',
      season: 'Spring',
      isFeatured: false,
      farmerId: farmerJohn.id,
    },
    {
      name: 'Dragon Fruit (Pitaya)',
      description: 'Exotic pink dragon fruit with a mild sweet taste and crunchy seeds.',
      category: 'Tropical',
      price: 8.99,
      stock: 12,
      unit: 'piece',
      image: 'https://images.unsplash.com/photo-1527325678964-54921661f92e?auto=format&fit=crop&w=600&q=80',
      calories: 50,
      protein: 1.2,
      carbs: 11,
      vitamins: 'Vitamin C, Iron, Magnesium',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerMaria.id,
    },
    {
      name: 'Wild Blueberries',
      description: 'Rich, antioxidant-packed wild blueberries, perfect for bowls and snacks.',
      category: 'Berries',
      price: 6.49,
      stock: 25,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?auto=format&fit=crop&w=600&q=80',
      calories: 57,
      protein: 0.7,
      carbs: 14,
      vitamins: 'Vitamin C, Vitamin K, Manganese',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerJohn.id,
    },
    {
      name: 'Organic Watermelon',
      description: 'Mega juicy, sweet and thirst-quenching watermelon from the hills of Hood River.',
      category: 'Melons',
      price: 7.99,
      stock: 8,
      unit: 'piece',
      image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
      calories: 30,
      protein: 0.6,
      carbs: 8,
      vitamins: 'Vitamin C, Vitamin A, Potassium',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerKen.id,
    },

    // --- 30 Indian-Specific Fruits ---
    {
      name: 'Ratnagiri Alphonso Mangoes',
      description: 'The legendary Hapus mango from Ratnagiri. Rich, creamy, saffron-colored pulp with an intensely sweet aroma.',
      category: 'Tropical',
      price: 12.99,
      stock: 40,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
      calories: 60,
      protein: 0.8,
      carbs: 15,
      vitamins: 'Vitamin A, Vitamin C, Vitamin E',
      season: 'Summer',
      isFeatured: true,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Gir Kesar Mangoes',
      description: 'Queen of mangoes from Gujarat. Fiberless, aromatic orange flesh that melts in your mouth.',
      category: 'Tropical',
      price: 9.99,
      stock: 35,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1605000797499-95a51c7769ae?auto=format&fit=crop&w=600&q=80',
      calories: 62,
      protein: 0.7,
      carbs: 16,
      vitamins: 'Vitamin C, Vitamin B6, Potassium',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Kashmiri Royal Gala Apples',
      description: 'Extremely crisp and sweet apples grown in the cold Shimla/Kashmir heights.',
      category: 'Stone Fruit',
      price: 4.49,
      stock: 60,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
      calories: 52,
      protein: 0.3,
      carbs: 14,
      vitamins: 'Vitamin C, Potassium, Iron',
      season: 'Autumn',
      isFeatured: true,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Nagpur Mandarin Oranges',
      description: 'World-famous Nagpur Santra. Loose skin, exceptionally juicy segments, and a perfect sweet-sour balance.',
      category: 'Citrus',
      price: 3.29,
      stock: 90,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=600&q=80',
      calories: 43,
      protein: 0.8,
      carbs: 10,
      vitamins: 'Vitamin C, Folate, Potassium',
      season: 'Winter',
      isFeatured: true,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Mahabaleshwar Sweet Strawberries',
      description: 'Lush red strawberries grown in the cool climate of Mahabaleshwar. Incredibly sweet and fresh.',
      category: 'Berries',
      price: 5.49,
      stock: 45,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
      calories: 33,
      protein: 0.7,
      carbs: 8,
      vitamins: 'Vitamin C, Manganese, Antioxidants',
      season: 'Winter',
      isFeatured: true,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Allahabad Safeda Guavas',
      description: 'Premium guavas with sweet, white flesh, high vitamin C content, and smooth green-yellow skin.',
      category: 'Tropical',
      price: 2.99,
      stock: 40,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      calories: 68,
      protein: 2.6,
      carbs: 14,
      vitamins: 'Vitamin C, Fiber, Vitamin A',
      season: 'Winter',
      isFeatured: false,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Solapur Ruby Pomegranates',
      description: 'Deep ruby-red arils with soft seeds. Extraordinarily sweet and packed with natural antioxidants.',
      category: 'Tropical',
      price: 6.49,
      stock: 55,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
      calories: 83,
      protein: 1.7,
      carbs: 19,
      vitamins: 'Vitamin C, Vitamin K, Folate',
      season: 'Autumn',
      isFeatured: true,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Shimla Golden Delicious Apples',
      description: 'A beautiful sweet yellow apple, with thin skin and juicy honey-tasting notes from Shimla orchards.',
      category: 'Stone Fruit',
      price: 4.29,
      stock: 50,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&w=600&q=80',
      calories: 53,
      protein: 0.3,
      carbs: 14,
      vitamins: 'Vitamin C, Potassium, Fiber',
      season: 'Autumn',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Kashmiri Sweet Cherries',
      description: 'Lush dark red cherries hand-sorted in Kashmir. Plump, juicy, and highly seasonal.',
      category: 'Stone Fruit',
      price: 7.99,
      stock: 30,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80',
      calories: 50,
      protein: 1.0,
      carbs: 12,
      vitamins: 'Vitamin C, Potassium, Iron',
      season: 'Summer',
      isFeatured: true,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Jalgaon Golden Bananas',
      description: 'Sweet, organic Cavendish bananas grown in Jalgaon, the banana hub of Maharashtra.',
      category: 'Tropical',
      price: 1.79,
      stock: 100,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      calories: 89,
      protein: 1.1,
      carbs: 23,
      vitamins: 'Vitamin B6, Manganese, Potassium',
      season: 'All',
      isFeatured: false,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Muzaffarpur Shahi Litchi',
      description: 'Sweetest litchi fruit from Bihar. Thin skin, translucent flesh, and unique floral scent.',
      category: 'Tropical',
      price: 5.99,
      stock: 30,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1587334274328-64186a80aeee?auto=format&fit=crop&w=600&q=80',
      calories: 66,
      protein: 0.8,
      carbs: 17,
      vitamins: 'Vitamin C, Copper, Potassium',
      season: 'Summer',
      isFeatured: true,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Tezpur Sweet Litchi',
      description: 'Premium organic litchi from Assam, known for its extra large size and extremely sweet pulp.',
      category: 'Tropical',
      price: 6.49,
      stock: 25,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1587334274328-64186a80aeee?auto=format&fit=crop&w=600&q=80',
      calories: 66,
      protein: 0.8,
      carbs: 17,
      vitamins: 'Vitamin C, Potassium',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Coorg Mandarin Oranges',
      description: 'Geographically certified Coorg oranges. Very sweet, rich orange color, and fragrant rind.',
      category: 'Citrus',
      price: 3.99,
      stock: 50,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80',
      calories: 45,
      protein: 0.7,
      carbs: 11,
      vitamins: 'Vitamin C, Vitamin A',
      season: 'Winter',
      isFeatured: false,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Bangalore Blue Grapes',
      description: 'Authentic Indian purple grapes with a deep sweet flavor, perfect for healthy snacking.',
      category: 'Stone Fruit',
      price: 4.79,
      stock: 65,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',
      calories: 69,
      protein: 0.7,
      carbs: 18,
      vitamins: 'Vitamin C, Vitamin K',
      season: 'Spring',
      isFeatured: true,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Dahanu Gholvad Chikoos',
      description: 'Sweet, granular sapodilla fruits from coastal Maharashtra. Rich in calcium and iron.',
      category: 'Tropical',
      price: 2.89,
      stock: 80,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80',
      calories: 83,
      protein: 0.4,
      carbs: 20,
      vitamins: 'Vitamin A, Vitamin C, Calcium',
      season: 'All',
      isFeatured: false,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Vazhakulam Sweet Pineapple',
      description: 'Geographically indicated Vazhakulam pineapple, sweet with low acidity and delicious aroma.',
      category: 'Tropical',
      price: 3.49,
      stock: 40,
      unit: 'piece',
      image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=600&q=80',
      calories: 50,
      protein: 0.5,
      carbs: 13,
      vitamins: 'Vitamin C, Manganese, Vitamin B6',
      season: 'All',
      isFeatured: true,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Khasi Mandarin',
      description: 'Exquisite loose-jacket oranges from the valleys of Meghalaya. Highly juicy and sweet.',
      category: 'Citrus',
      price: 4.19,
      stock: 35,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?auto=format&fit=crop&w=600&q=80',
      calories: 47,
      protein: 0.8,
      carbs: 12,
      vitamins: 'Vitamin C, Potassium',
      season: 'Winter',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Tripura Queen Pineapple',
      description: 'Golden yellow, crisp, and exceptionally sweet pineapple variety grown in Tripura hills.',
      category: 'Tropical',
      price: 3.79,
      stock: 30,
      unit: 'piece',
      image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=600&q=80',
      calories: 52,
      protein: 0.5,
      carbs: 14,
      vitamins: 'Vitamin C, Fiber',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Nashik Valley Seedless Grapes',
      description: 'Plump, crispy, and sweet green table grapes direct from Nashik orchards.',
      category: 'Stone Fruit',
      price: 3.99,
      stock: 75,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',
      calories: 67,
      protein: 0.6,
      carbs: 17,
      vitamins: 'Vitamin K, Vitamin C, Antioxidants',
      season: 'Spring',
      isFeatured: false,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Black Jamun (Indian Blackberry)',
      description: 'Sweet and tangy wild berries with dark purple skins, traditionally valued for wellness.',
      category: 'Berries',
      price: 6.99,
      stock: 25,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=600&q=80',
      calories: 60,
      protein: 0.7,
      carbs: 14,
      vitamins: 'Vitamin C, Iron, Calcium',
      season: 'Summer',
      isFeatured: true,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Custard Apple (Sitaphal)',
      description: 'Lumpy green skin hiding a rich, creamy, and custard-like sweet white pulp.',
      category: 'Tropical',
      price: 5.49,
      stock: 30,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80',
      calories: 94,
      protein: 2.1,
      carbs: 23,
      vitamins: 'Vitamin C, Vitamin B6, Magnesium',
      season: 'Autumn',
      isFeatured: true,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Sweet Papaya',
      description: 'Vibrant orange flesh, incredibly sweet, buttery texture, harvested in Nagpur.',
      category: 'Tropical',
      price: 2.49,
      stock: 50,
      unit: 'piece',
      image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=600&q=80',
      calories: 43,
      protein: 0.5,
      carbs: 11,
      vitamins: 'Vitamin A, Vitamin C, Folate',
      season: 'All',
      isFeatured: false,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Indian Fig (Anjeer)',
      description: 'Rich, sweet, and soft fresh figs grown organic in the central dry regions.',
      category: 'Tropical',
      price: 5.99,
      stock: 20,
      unit: 'pack',
      image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80',
      calories: 74,
      protein: 0.8,
      carbs: 19,
      vitamins: 'Fiber, Calcium, Potassium',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Spiced Bael (Wood Apple)',
      description: 'Nutritious woody-shelled bael fruit, famous for its refreshing sweet pulp.',
      category: 'Tropical',
      price: 2.99,
      stock: 30,
      unit: 'piece',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      calories: 137,
      protein: 1.8,
      carbs: 31,
      vitamins: 'Vitamin C, Riboflavin',
      season: 'Spring',
      isFeatured: false,
      farmerId: farmerDevendra.id,
    },
    {
      name: 'Jalgaon Red Bananas',
      description: 'Rare exotic red banana from Jalgaon, boasting a sweet berry-like cream flavor.',
      category: 'Tropical',
      price: 3.49,
      stock: 40,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      calories: 89,
      protein: 1.1,
      carbs: 23,
      vitamins: 'Vitamin C, Vitamin B6',
      season: 'All',
      isFeatured: true,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Banarasi Sweet Gooseberry',
      description: 'Large, translucent Banarasi Aonla. Extremely rich source of Vitamin C and antioxidants.',
      category: 'Citrus',
      price: 2.49,
      stock: 80,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=600&q=80',
      calories: 44,
      protein: 0.9,
      carbs: 10,
      vitamins: 'Vitamin C, Vitamin A, Calcium',
      season: 'Winter',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Langra Mangoes (Malda)',
      description: 'Famous green-skinned Langra mangoes. Highly sweet, fiberless lemon-yellow flesh with intense aroma.',
      category: 'Tropical',
      price: 7.49,
      stock: 35,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
      calories: 60,
      protein: 0.8,
      carbs: 15,
      vitamins: 'Vitamin A, Vitamin C',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Himsagar Mangoes',
      description: 'Sweet aromatic Bengal mango, highly prized for its smooth texture and rich tropical taste.',
      category: 'Tropical',
      price: 8.29,
      stock: 30,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1605000797499-95a51c7769ae?auto=format&fit=crop&w=600&q=80',
      calories: 62,
      protein: 0.8,
      carbs: 16,
      vitamins: 'Vitamin C, Vitamin A',
      season: 'Summer',
      isFeatured: false,
      farmerId: farmerRajesh.id,
    },
    {
      name: 'Nendran Banana (Kerala)',
      description: 'Thick, starchy bananas, famous in Kerala. Great for steaming or making banana chips.',
      category: 'Tropical',
      price: 2.59,
      stock: 60,
      unit: 'kg',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      calories: 95,
      protein: 1.2,
      carbs: 24,
      vitamins: 'Vitamin B6, Potassium',
      season: 'All',
      isFeatured: false,
      farmerId: farmerSunita.id,
    },
    {
      name: 'Allahabad Safeda Guava Honey',
      description: 'Infused guava nectar, pure and organic, direct from the fields of Allahabad.',
      category: 'Tropical',
      price: 6.99,
      stock: 20,
      unit: 'jar',
      image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
      calories: 120,
      protein: 0.2,
      carbs: 30,
      vitamins: 'Vitamin C, Potassium',
      season: 'All',
      isFeatured: false,
      farmerId: farmerDevendra.id,
    }
  ];

  for (const prod of products) {
    const createdProduct = await prisma.product.create({
      data: prod,
    });

    // Seed some reviews
    await prisma.review.create({
      data: {
        userId: customer.id,
        productId: createdProduct.id,
        rating: 5,
        comment: `Absolutely loved this! The ${createdProduct.name.toLowerCase()} was fresh, ripe and delicious.`,
      },
    });
  }

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
